apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rsenvcomp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rs-demos-xvbe-tenant/rsenvapp/rsenvcomp@sha256:a230a381a171d8ec2c44448f5b65905b5ac837f43ee06e1b4c44717a3119cee6
        name: my-java-quarkus
        resources: {}
status: {}
